#!/bin/bash

# Clone upstream
git clone https://github.com/saljam/webwormhole.git upstream
cd upstream

# Install bagop
curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
install /tmp/bagop /usr/local/bin

# Build release
CGO_ENABLED=0 GO386=softfloat bagop -b ww -x '(android/*|ios/*|openbsd/mips64|js/wasm)' -p "go build -a -ldflags '-extldflags \"-static\"' -o \$DST ./cmd/ww"

# Stage binaries
cd ..
mv upstream/out .
