name: Go CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build with Go
        run: |
          git clone https://github.com/saljam/webwormhole.git upstream
          cd upstream

          GOOS=linux GOARCH=amd64 go build -o staging/ww.linux-amd64 ./cmd/ww
          GOOS=linux GOARCH=arm64 go build -o staging/ww.linux-arm64 ./cmd/ww
          GOOS=windows GOARCH=amd64 go build -o staging/ww.windows-amd64.exe ./cmd/ww
          GOOS=darwin GOARCH=amd64 go build -o staging/ww.darwin-amd64 ./cmd/ww
          GOOS=darwin GOARCH=arm64 go build -o staging/ww.darwin-arm64 ./cmd/ww
      - name: Publish binaries to GitHub releases
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            staging/*
